// Generated by CoffeeScript 1.6.1
(function() {
  var rollInText;

  $(document).ready(function() {
    return $("#me-img").load(function() {
      $("#me-img").hide().fadeIn(800);
      $("nav").hide().fadeIn(800);
      return setTimeout(rollInText, 600);
    });
  });

  rollInText = function() {
    return $(".text-shader-1").addClass("text-shader-active");
  };

}).call(this);
