// Generated by CoffeeScript 1.9.3
(function() {
  var rollInText;

  $(document).ready(function() {
    return $("#me-img").load(function() {
      return setTimeout(rollInText, 600);
    });
  });

  rollInText = function() {
    return $(".text-shader-1").addClass("text-shader-active");
  };

}).call(this);
