// Generated by CoffeeScript 1.6.1
(function() {
  var addNav, loadPage, rollInText, setAndBindDimensions;

  $(document).ready(function() {
    return loadPage();
  });

  setAndBindDimensions = function() {
    var setDimensions;
    setDimensions = function() {
      var height;
      height = $(window).height();
      if (height > 550) {
        return $(".me-footer").css({
          "visibility": "visible",
          "position": "absolute",
          "bottom": "40px"
        });
      } else {
        return $(".me-footer").css({
          "visibility": "hidden"
        });
      }
    };
    $(window).bind('resize', function() {
      return setDimensions();
    });
    return setDimensions();
  };

  rollInText = function() {
    return $(".text-shader-1").addClass("text-shader-active");
  };

  addNav = function() {};

  loadPage = function() {
    setAndBindDimensions();
    return setTimeout(rollInText, 600);
  };

}).call(this);
